import {
  UserProfile,
  C3Centre,
  ServiceTeam,
  MinistryTeam,
  C3Report,
  ServiceTeamReport,
  MinistryReport,
  GeneralServiceReport,
} from './types';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user-resident-pastor',
    fullName: 'Pastor David Terzungwe',
    email: 'resident.pastor@cfcmakurdi.org',
    phone: '+234 803 123 4567',
    role: 'resident_pastor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-assoc-c3',
    fullName: 'Pastor Emmanuel Ogwuche',
    email: 'assoc.c3@cfcmakurdi.org',
    phone: '+234 802 234 5678',
    role: 'associate_pastor_c3',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-assoc-teams',
    fullName: 'Pastor Samuel Iorkase',
    email: 'assoc.teams@cfcmakurdi.org',
    phone: '+234 805 345 6789',
    role: 'associate_pastor_service_teams',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-c3-wurukum',
    fullName: 'Minister Faith Terungwa',
    email: 'faith.c3@cfcmakurdi.org',
    phone: '+234 813 456 7890',
    role: 'c3_minister',
    c3Id: 'c3-wurukum',
    c3Name: 'C3 Wurukum Grace Center',
  },
  {
    id: 'user-c3-highlevel',
    fullName: 'Minister Joshua Idoko',
    email: 'joshua.highlevel@cfcmakurdi.org',
    phone: '+234 814 567 8901',
    role: 'c3_minister',
    c3Id: 'c3-highlevel',
    c3Name: 'C3 High-Level Faith Hub',
  },
  {
    id: 'user-team-choir',
    fullName: 'Bro. Gabriel Onoja',
    email: 'choir.lead@cfcmakurdi.org',
    phone: '+234 816 678 9012',
    role: 'service_team_leader',
    serviceTeamId: 'team-choir',
    serviceTeamName: 'Choir (Sound of Judah)',
  },
  {
    id: 'user-team-ushers',
    fullName: 'Sis. Grace Kave',
    email: 'ushering.lead@cfcmakurdi.org',
    phone: '+234 817 789 0123',
    role: 'service_team_leader',
    serviceTeamId: 'team-ushers',
    serviceTeamName: 'Ushering & Greeters',
  },
  {
    id: 'user-team-media',
    fullName: 'Bro. Daniel Aondo',
    email: 'media.lead@cfcmakurdi.org',
    phone: '+234 818 890 1234',
    role: 'service_team_leader',
    serviceTeamId: 'team-media',
    serviceTeamName: 'Media & Technical',
  },
  {
    id: 'user-ministry-men',
    fullName: 'Elder Abraham Chia',
    email: 'men.fellowship@cfcmakurdi.org',
    phone: '+234 809 901 2345',
    role: 'ministry_leader',
    ministryId: 'min-men',
    ministryName: 'Men of Faith Fellowship',
  },
  {
    id: 'user-ministry-ladies',
    fullName: 'Deaconess Blessing Terungwa',
    email: '31stladies@cfcmakurdi.org',
    phone: '+234 808 012 3456',
    role: 'ministry_leader',
    ministryId: 'min-ladies',
    ministryName: '31st Ladies Fellowship',
  },
  {
    id: 'user-ministry-children',
    fullName: 'Sis. Rosemary Abah',
    email: 'children.church@cfcmakurdi.org',
    phone: '+234 807 123 9876',
    role: 'ministry_leader',
    ministryId: 'min-children',
    ministryName: "Children's Church (Kingdom Kids)",
  },
];

export const MOCK_C3_CENTRES: C3Centre[] = [
  {
    id: 'c3-wurukum',
    name: 'C3 Wurukum Grace Center',
    zone: 'Wurukum',
    meetingAddress: 'No. 14 Gboko Road, Wurukum, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Bro. Terungwa Aondo',
    ministerName: 'Minister Faith Terungwa',
    isActive: true,
  },
  {
    id: 'c3-highlevel',
    name: 'C3 High-Level Faith Hub',
    zone: 'High-Level',
    meetingAddress: 'Opposite Modern Market Roundabout, High-Level, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:30 PM',
    hostName: 'Sis. Deborah Iorhemen',
    ministerName: 'Minister Joshua Idoko',
    isActive: true,
  },
  {
    id: 'c3-northbank',
    name: 'C3 North-Bank Victory Cell',
    zone: 'North-Bank',
    meetingAddress: 'Near University of Agriculture Junction, North-Bank, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Bro. Emmanuel Agbo',
    ministerName: 'Minister Timothy Bem',
    isActive: true,
  },
  {
    id: 'c3-kanshio',
    name: 'C3 Kanshio Covenant Assembly',
    zone: 'Kanshio',
    meetingAddress: 'Behind Federal Low Cost, Kanshio, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Elder Peter Ochigbo',
    ministerName: 'Minister Peter Ochigbo',
    isActive: true,
  },
  {
    id: 'c3-judges',
    name: 'C3 Judges Quarters Peace Unit',
    zone: 'Judges Quarters',
    meetingAddress: 'Plot 8, GRA Extension, Judges Quarters, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '6:00 PM',
    hostName: 'Deaconess Comfort Chia',
    ministerName: 'Minister Comfort Chia',
    isActive: true,
  },
  {
    id: 'c3-modernmarket',
    name: 'C3 Modern Market Dominion Cell',
    zone: 'Modern Market',
    meetingAddress: 'Beside Railway Line, Modern Market Area, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:15 PM',
    hostName: 'Bro. Joshua Terver',
    ministerName: 'Minister Paul Hembadoon',
    isActive: true,
  },
];

export const MOCK_SERVICE_TEAMS: ServiceTeam[] = [
  {
    id: 'team-choir',
    name: 'Choir (Sound of Judah)',
    code: 'CHOIR',
    description: 'Praise & Worship team leading prophetic atmosphere and worship sessions',
    leaderName: 'Bro. Gabriel Onoja',
    isActive: true,
  },
  {
    id: 'team-ushers',
    name: 'Ushering & Greeters',
    code: 'USHERS',
    description: 'Sanctuary seating, welcoming congregants, offering coordination & orderly crowd flow',
    leaderName: 'Sis. Grace Kave',
    isActive: true,
  },
  {
    id: 'team-media',
    name: 'Media & Technical',
    code: 'MEDIA',
    description: 'Sound engineering, live streaming, multi-camera videography, acoustics and projection',
    leaderName: 'Bro. Daniel Aondo',
    isActive: true,
  },
  {
    id: 'team-sanctuary',
    name: 'Sanctuary Keepers',
    code: 'SANCTUARY',
    description: 'Beautification, cleanliness, and ambiance of church auditorium and surroundings',
    leaderName: 'Sis. Esther Igoche',
    isActive: true,
  },
  {
    id: 'team-protocol',
    name: 'Protocol & Pastoral Care',
    code: 'PROTOCOL',
    description: 'Guest ministers reception, pulpit protocol, orderly guidance during altar calls',
    leaderName: 'Bro. Victor Ayila',
    isActive: true,
  },
  {
    id: 'team-security',
    name: 'Traffic & Security',
    code: 'SECURITY',
    description: 'Vehicle parking management, perimeter security, surveillance and safe dispersal',
    leaderName: 'Capt. Isaac Tyopev (Rtd)',
    isActive: true,
  },
  {
    id: 'team-welfare',
    name: 'Welfare & Member Assimilation',
    code: 'WELFARE',
    description: 'Hospitality to visitors, benevolence support, and pastoral check-ins',
    leaderName: 'Deaconess Martha Kula',
    isActive: true,
  },
];

export const MOCK_MINISTRY_TEAMS: MinistryTeam[] = [
  {
    id: 'min-men',
    name: 'Men of Faith Fellowship',
    code: 'MEN',
    description: 'Empowerment, spiritual mentorship, career growth and family leadership for men',
    targetAudience: 'Christian Men & Fathers',
    leaderName: 'Elder Abraham Chia',
    isActive: true,
  },
  {
    id: 'min-ladies',
    name: '31st Ladies Fellowship',
    code: 'LADIES',
    description: 'Virtuous women ministry, spiritual retreats, marriage health, and sisterly support',
    targetAudience: 'Christian Women & Mothers',
    leaderName: 'Deaconess Blessing Terungwa',
    isActive: true,
  },
  {
    id: 'min-children',
    name: "Children's Church (Kingdom Kids)",
    code: 'CHILDREN',
    description: 'Age-tailored biblical instruction, foundational discipleship, crafts, and memory verses',
    targetAudience: 'Children aged 1 to 12',
    leaderName: 'Sis. Rosemary Abah',
    isActive: true,
  },
];

export const MOCK_C3_REPORTS: C3Report[] = [
  {
    id: 'c3rep-001',
    c3Id: 'c3-wurukum',
    c3Name: 'C3 Wurukum Grace Center',
    zone: 'Wurukum',
    meetingDate: '2026-09-23',
    topicTaught: 'Walking in Supernatural Dominion: Part 3',
    maleAttendance: 11,
    femaleAttendance: 14,
    childrenAttendance: 7,
    totalAttendance: 32,
    firstTimers: 3,
    newConverts: 1,
    offeringAmount: 18500,
    tithesAmount: 25000,
    prayerRequests: 'Healing for Mama Iorbee admitted at FMC Makurdi. Job breakthrough for Bro Joseph.',
    testimonies: 'Sis. Jennifer testified of surviving a vehicle breakdown on Makurdi-Aliade expressway safely.',
    challengesEncountered: 'Generator fuel price increase affected power during the fellowship.',
    submittedBy: 'user-c3-wurukum',
    submittedByName: 'Minister Faith Terungwa',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'Commended for consistent attendance growth and follow-up on FMC hospital visit.',
    residentPastorNotes: 'Great work Wurukum cell. Pastoral team will visit Mama Iorbee at FMC.',
    createdAt: '2026-09-23T20:30:00Z',
    updatedAt: '2026-09-24T10:15:00Z',
  },
  {
    id: 'c3rep-002',
    c3Id: 'c3-highlevel',
    c3Name: 'C3 High-Level Faith Hub',
    zone: 'High-Level',
    meetingDate: '2026-09-23',
    topicTaught: 'The Power of Collective Intercession',
    maleAttendance: 9,
    femaleAttendance: 16,
    childrenAttendance: 5,
    totalAttendance: 30,
    firstTimers: 4,
    newConverts: 2,
    offeringAmount: 22000,
    tithesAmount: 15000,
    prayerRequests: 'Prayers for student members taking university semester examinations.',
    testimonies: 'Bro. Terna secured employment with an agribusiness firm in Makurdi.',
    challengesEncountered: 'Space constraints in living room due to growing attendance. Looking at outdoor canopy option.',
    submittedBy: 'user-c3-highlevel',
    submittedByName: 'Minister Joshua Idoko',
    status: 'reviewed_by_associate',
    associatePastorNotes: 'Recommending cell multiplication into High-Level 2 before Q4.',
    createdAt: '2026-09-23T21:10:00Z',
    updatedAt: '2026-09-24T08:30:00Z',
  },
  {
    id: 'c3rep-003',
    c3Id: 'c3-northbank',
    c3Name: 'C3 North-Bank Victory Cell',
    zone: 'North-Bank',
    meetingDate: '2026-09-23',
    topicTaught: 'Faith That Overcomes Trials',
    maleAttendance: 8,
    femaleAttendance: 10,
    childrenAttendance: 6,
    totalAttendance: 24,
    firstTimers: 2,
    newConverts: 0,
    offeringAmount: 12500,
    tithesAmount: 0,
    prayerRequests: 'Peace in surrounding neighborhoods and security along new bypass.',
    testimonies: 'Bro. Emmanuel passed professional licensing board exam.',
    challengesEncountered: 'Heavy downpour starting at 4:45 PM reduced arrival count.',
    submittedBy: 'user-c3-northbank',
    submittedByName: 'Minister Timothy Bem',
    status: 'submitted',
    createdAt: '2026-09-23T22:00:00Z',
    updatedAt: '2026-09-23T22:00:00Z',
  },
  {
    id: 'c3rep-004',
    c3Id: 'c3-kanshio',
    c3Name: 'C3 Kanshio Covenant Assembly',
    zone: 'Kanshio',
    meetingDate: '2026-09-23',
    topicTaught: 'Financial Stewardship and the Blessing',
    maleAttendance: 12,
    femaleAttendance: 15,
    childrenAttendance: 8,
    totalAttendance: 35,
    firstTimers: 5,
    newConverts: 2,
    offeringAmount: 26000,
    tithesAmount: 40000,
    prayerRequests: 'Family reconciliation request for the Agada household.',
    testimonies: 'Safe child delivery for Sis Mercy Ochigbo at Bishop Murray Hospital.',
    challengesEncountered: 'Need more hymn sheets and discipleship manuals for first timers.',
    submittedBy: 'user-c3-kanshio',
    submittedByName: 'Minister Peter Ochigbo',
    status: 'submitted',
    createdAt: '2026-09-24T07:45:00Z',
    updatedAt: '2026-09-24T07:45:00Z',
  },
];

export const MOCK_SERVICE_TEAM_REPORTS: ServiceTeamReport[] = [
  {
    id: 'st-rep-001',
    teamId: 'team-choir',
    teamName: 'Choir (Sound of Judah)',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 26,
    rosterAbsentCount: 3,
    totalOnDuty: 26,
    tasksCompleted: 'Led 40-minute praise & prophetic worship. Backed up special ministration. Rehearsed 2 new anthem arrangements.',
    equipmentStatus: 'All 8 wireless microphones worked properly. Keyboard sustain pedal had minor intermittent contact.',
    challengesEncountered: 'Bass amp showed slight ground buzz in the second half of service.',
    urgentNeeds: 'Replacement 9V rechargeable batteries for lead vocal mics.',
    submittedBy: 'user-team-choir',
    submittedByName: 'Bro. Gabriel Onoja',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'Commended worship flow. Sound team resolved the pedal cable after service.',
    residentPastorNotes: 'The atmosphere was divine. Battery procurement approved.',
    createdAt: '2026-09-27T12:30:00Z',
    updatedAt: '2026-09-27T16:00:00Z',
  },
  {
    id: 'st-rep-002',
    teamId: 'team-ushers',
    teamName: 'Ushering & Greeters',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 22,
    rosterAbsentCount: 2,
    totalOnDuty: 22,
    tasksCompleted: 'Managed auditorium seating capacity of 650. Handled 3 waves of offering collection. Ushered 48 first timers to reception hall.',
    equipmentStatus: 'All handheld offering pouches, velvet counting bags, and guest badges in good condition.',
    challengesEncountered: 'Overflow gallery filled up 15 minutes before sermon; required fast deployment of spare plastic chairs.',
    urgentNeeds: 'Additional 30 branded ushering lapel pins and first timer visitor gift packets.',
    submittedBy: 'user-team-ushers',
    submittedByName: 'Sis. Grace Kave',
    status: 'reviewed_by_associate',
    associatePastorNotes: 'Great agility during overflow seating. Visitor packets requisition forwarded to Admin.',
    createdAt: '2026-09-27T13:15:00Z',
    updatedAt: '2026-09-27T15:20:00Z',
  },
  {
    id: 'st-rep-003',
    teamId: 'team-media',
    teamName: 'Media & Technical',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 14,
    rosterAbsentCount: 1,
    totalOnDuty: 14,
    tasksCompleted: 'Full HD multi-camera broadcast on YouTube and Facebook Live (Peak 340 concurrent viewers). Recorded sermon podcast. Managed LED video wall.',
    equipmentStatus: 'Main audio mixer firmware updated. Camera 2 HDMI converter cable replaced.',
    challengesEncountered: 'Starlink satellite link had 12-second latency spike during opening prayer due to cloud cover.',
    urgentNeeds: 'High-speed SD cards for auxiliary raw camera archives.',
    submittedBy: 'user-team-media',
    submittedByName: 'Bro. Daniel Aondo',
    status: 'submitted',
    createdAt: '2026-09-27T14:00:00Z',
    updatedAt: '2026-09-27T14:00:00Z',
  },
];

export const MOCK_MINISTRY_REPORTS: MinistryReport[] = [
  {
    id: 'minrep-001',
    ministryId: 'min-men',
    ministryName: 'Men of Faith Fellowship',
    meetingDate: '2026-09-20',
    reportTitle: 'September Men Breakfast & Wealth Creation Summit',
    totalAttendance: 78,
    firstTimers: 9,
    offeringAmount: 95000,
    activitiesSummary: 'Organized practical business seminar on Commercial Grain Storage & Distribution in Benue State. Followed by intense prayer for family prosperity.',
    spiritualHighlights: '3 men dedicated their businesses to the Lord; one brother received salvation during the breakfast session.',
    upcomingPrograms: 'Annual Men of Faith Camp Retreat scheduled for November 14-16 at Canaan Land Camp, Makurdi.',
    challengesAndRequests: 'Requesting church bus support for transporting men living in North-Bank and Judges Quarters for the upcoming retreat.',
    submittedBy: 'user-ministry-men',
    submittedByName: 'Elder Abraham Chia',
    status: 'approved_by_resident_pastor',
    pastoralNotes: 'Excellent initiative connecting faith and economic empowerment. Church bus logistics approved for the retreat.',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-21T18:00:00Z',
  },
  {
    id: 'minrep-002',
    ministryId: 'min-ladies',
    ministryName: '31st Ladies Fellowship',
    meetingDate: '2026-09-19',
    reportTitle: 'Monthly Daughters of Zion Prayer Vigil & Health Screening',
    totalAttendance: 112,
    firstTimers: 14,
    offeringAmount: 82000,
    activitiesSummary: 'Free blood pressure and diabetes screening for mothers. Spiritual charge on "The Deborah Anointing in Trying Times" delivered by Resident Pastor\'s Wife.',
    spiritualHighlights: 'Strong move of the Spirit during the midnight intercessory session for marital breakthroughs.',
    upcomingPrograms: 'Widows and Elderly Care Outreach scheduled for October 10th.',
    challengesAndRequests: 'Need welfare pantry replenishment of food grains (rice, beans, yams) for the October outreach.',
    submittedBy: 'user-ministry-ladies',
    submittedByName: 'Deaconess Blessing Terungwa',
    status: 'approved_by_resident_pastor',
    pastoralNotes: 'Commended for combining medical checkups with intense prayers. Welfare department has been instructed to partner on grain provision.',
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-09-21T14:30:00Z',
  },
  {
    id: 'minrep-003',
    ministryId: 'min-children',
    ministryName: "Children's Church (Kingdom Kids)",
    meetingDate: '2026-09-27',
    reportTitle: 'Sunday School & Kingdom Kids Celebration',
    totalAttendance: 146,
    firstTimers: 18,
    offeringAmount: 24500,
    activitiesSummary: 'Age-graded bible classes (Toddlers, Beginners, Primaries, Juniors). Theme: "David and Goliath - Courage to Overcome". Color-in memory verse booklets.',
    spiritualHighlights: '12 older children (Ages 9-11) recited the entire Psalm 91 from memory.',
    upcomingPrograms: 'Children Christmas Musical Drama rehearsals starting first week of October.',
    challengesAndRequests: 'Need 2 additional teachers for the Beginner class (Ages 3-5) to maintain ideal teacher-to-child ratio.',
    submittedBy: 'user-ministry-children',
    submittedByName: 'Sis. Rosemary Abah',
    status: 'submitted',
    createdAt: '2026-09-27T13:45:00Z',
    updatedAt: '2026-09-27T13:45:00Z',
  },
];

export const MOCK_GENERAL_SERVICES: GeneralServiceReport[] = [
  {
    id: 'gen-001',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    preacher: 'Pastor David Terzungwe',
    sermonTitle: 'Unlocking Supernatural Supply in Economic Seasons',
    maleCount: 245,
    femaleCount: 310,
    childrenCount: 146,
    totalAttendance: 701,
    firstTimersCount: 48,
    newConvertsCount: 17,
    totalOffering: 385000,
    totalTithe: 760000,
    notes: 'Exceptional atmosphere. 17 souls responded to the altar call. Altar counselors engaged all first timers.',
    submittedByName: 'Pastor David Terzungwe',
    createdAt: '2026-09-27T14:30:00Z',
  },
  {
    id: 'gen-002',
    serviceDate: '2026-09-20',
    serviceType: 'first_service',
    preacher: 'Pastor Emmanuel Ogwuche',
    sermonTitle: 'The Believer’s Covenant Immunity',
    maleCount: 230,
    femaleCount: 295,
    childrenCount: 138,
    totalAttendance: 663,
    firstTimersCount: 36,
    newConvertsCount: 11,
    totalOffering: 340000,
    totalTithe: 620000,
    notes: 'Communion service with deep healing testimonies shared.',
    submittedByName: 'Pastor Emmanuel Ogwuche',
    createdAt: '2026-09-20T14:00:00Z',
  },
  {
    id: 'gen-003',
    serviceDate: '2026-09-13',
    serviceType: 'first_service',
    preacher: 'Pastor David Terzungwe',
    sermonTitle: 'Empowered for Exploits',
    maleCount: 218,
    femaleCount: 280,
    childrenCount: 125,
    totalAttendance: 623,
    firstTimersCount: 29,
    newConvertsCount: 8,
    totalOffering: 310000,
    totalTithe: 540000,
    notes: 'Anointing service. High student attendance.',
    submittedByName: 'Pastor David Terzungwe',
    createdAt: '2026-09-13T14:15:00Z',
  },
];

export const ATTENDANCE_TREND_DATA = [
  { week: 'Wk 1 (Sep 6)', Sunday: 590, C3Cells: 118, Volunteers: 84 },
  { week: 'Wk 2 (Sep 13)', Sunday: 623, C3Cells: 125, Volunteers: 88 },
  { week: 'Wk 3 (Sep 20)', Sunday: 663, C3Cells: 136, Volunteers: 92 },
  { week: 'Wk 4 (Sep 27)', Sunday: 701, C3Cells: 148, Volunteers: 98 },
];

export const C3_BREAKDOWN_DATA = [
  { name: 'Wurukum', attendance: 32, converts: 1, firstTimers: 3, offering: 18500 },
  { name: 'High-Level', attendance: 30, converts: 2, firstTimers: 4, offering: 22000 },
  { name: 'North-Bank', attendance: 24, converts: 0, firstTimers: 2, offering: 12500 },
  { name: 'Kanshio', attendance: 35, converts: 2, firstTimers: 5, offering: 26000 },
  { name: 'Judges Qtrs', attendance: 28, converts: 1, firstTimers: 2, offering: 21000 },
  { name: 'Modern Mkt', attendance: 22, converts: 1, firstTimers: 1, offering: 14000 },
];
