import {
  UserProfile,
  C3Centre,
  ServiceTeam,
  MinistryTeam,
  C3Report,
  ServiceTeamReport,
  MinistryReport,
  GeneralServiceReport,
} from './types';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user-resident-pastor',
    fullName: 'Pastor David Terzungwe',
    email: 'resident.pastor@cfcmakurdi.org',
    phone: '+234 803 123 4567',
    role: 'resident_pastor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-assoc-c3',
    fullName: 'Pastor Emmanuel Ogwuche',
    email: 'assoc.c3@cfcmakurdi.org',
    phone: '+234 802 234 5678',
    role: 'associate_pastor_c3',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-assoc-teams',
    fullName: 'Pastor Samuel Iorkase',
    email: 'assoc.teams@cfcmakurdi.org',
    phone: '+234 805 345 6789',
    role: 'associate_pastor_service_teams',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-c3-nyiman',
    fullName: 'Minister Faith Terungwa',
    email: 'faith.nyiman@cfcmakurdi.org',
    phone: '+234 813 456 7890',
    role: 'c3_minister',
    c3Id: 'c3-nyiman',
    c3Name: 'Nyiman C3',
  },
  {
    id: 'user-c3-georgeakume',
    fullName: 'Minister Joshua Idoko',
    email: 'joshua.gakume@cfcmakurdi.org',
    phone: '+234 814 567 8901',
    role: 'c3_minister',
    c3Id: 'c3-georgeakume',
    c3Name: 'George Akume Way C3',
  },
  {
    id: 'user-c3-northbank',
    fullName: 'Minister Timothy Bem',
    email: 'timothy.northbank@cfcmakurdi.org',
    phone: '+234 815 678 1234',
    role: 'c3_minister',
    c3Id: 'c3-northbank',
    c3Name: 'North Bank C3',
  },
  {
    id: 'user-c3-gyadovilla',
    fullName: 'Minister Peter Ochigbo',
    email: 'peter.gyadovilla@cfcmakurdi.org',
    phone: '+234 816 789 2345',
    role: 'c3_minister',
    c3Id: 'c3-gyadovilla',
    c3Name: 'Gyado Villa C3',
  },
  {
    id: 'user-c3-welfarequarters',
    fullName: 'Minister Comfort Chia',
    email: 'comfort.welfareqtrs@cfcmakurdi.org',
    phone: '+234 817 890 3456',
    role: 'c3_minister',
    c3Id: 'c3-welfarequarters',
    c3Name: 'Welfare Quarters C3',
  },
  {
    id: 'user-c3-oldgra',
    fullName: 'Minister Paul Hembadoon',
    email: 'paul.oldgra@cfcmakurdi.org',
    phone: '+234 818 901 4567',
    role: 'c3_minister',
    c3Id: 'c3-oldgra',
    c3Name: 'Old GRA C3',
  },
  {
    id: 'user-team-prayer',
    fullName: 'Pastor Mercy Agbese',
    email: 'prayer.lead@cfcmakurdi.org',
    phone: '+234 819 012 5678',
    role: 'service_team_leader',
    serviceTeamId: 'team-prayer',
    serviceTeamName: 'Prayer & Counselling',
  },
  {
    id: 'user-team-music',
    fullName: 'Bro. Gabriel Onoja',
    email: 'music.lead@cfcmakurdi.org',
    phone: '+234 816 678 9012',
    role: 'service_team_leader',
    serviceTeamId: 'team-music',
    serviceTeamName: 'Music (CFC Music)',
  },
  {
    id: 'user-team-production',
    fullName: 'Bro. Daniel Aondo',
    email: 'production.lead@cfcmakurdi.org',
    phone: '+234 818 890 1234',
    role: 'service_team_leader',
    serviceTeamId: 'team-production',
    serviceTeamName: 'Production (Media & Sound)',
  },
  {
    id: 'user-team-welfare',
    fullName: 'Deaconess Martha Kula',
    email: 'welfare.lead@cfcmakurdi.org',
    phone: '+234 817 789 0123',
    role: 'service_team_leader',
    serviceTeamId: 'team-welfare',
    serviceTeamName: 'Welfare',
  },
  {
    id: 'user-team-ushers',
    fullName: 'Sis. Grace Kave',
    email: 'ushering.lead@cfcmakurdi.org',
    phone: '+234 812 345 6789',
    role: 'service_team_leader',
    serviceTeamId: 'team-ushers',
    serviceTeamName: 'Ushering & Protocol',
  },
  {
    id: 'user-ministry-men',
    fullName: 'Elder Abraham Chia',
    email: 'men.fellowship@cfcmakurdi.org',
    phone: '+234 809 901 2345',
    role: 'ministry_leader',
    ministryId: 'min-men',
    ministryName: 'Men of Faith Fellowship',
  },
  {
    id: 'user-ministry-ladies',
    fullName: 'Deaconess Blessing Terungwa',
    email: '31stladies@cfcmakurdi.org',
    phone: '+234 808 012 3456',
    role: 'ministry_leader',
    ministryId: 'min-ladies',
    ministryName: '31st Ladies Fellowship',
  },
  {
    id: 'user-ministry-children',
    fullName: 'Sis. Rosemary Abah',
    email: 'children.church@cfcmakurdi.org',
    phone: '+234 807 123 9876',
    role: 'ministry_leader',
    ministryId: 'min-children',
    ministryName: "Children's Church (Kingdom Kids)",
  },
];

export const MOCK_C3_CENTRES: C3Centre[] = [
  {
    id: 'c3-nyiman',
    name: 'Nyiman C3',
    zone: 'Nyiman',
    meetingAddress: 'Off Abu King Shuluwa Road, Nyiman Layout, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Bro. Terungwa Aondo',
    ministerName: 'Minister Faith Terungwa',
    isActive: true,
  },
  {
    id: 'c3-georgeakume',
    name: 'George Akume Way C3',
    zone: 'George Akume Way',
    meetingAddress: 'Near New Garage Junction, George Akume Way, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:30 PM',
    hostName: 'Sis. Deborah Iorhemen',
    ministerName: 'Minister Joshua Idoko',
    isActive: true,
  },
  {
    id: 'c3-northbank',
    name: 'North Bank C3',
    zone: 'North Bank',
    meetingAddress: 'Near University of Agriculture Road, North Bank, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Bro. Emmanuel Agbo',
    ministerName: 'Minister Timothy Bem',
    isActive: true,
  },
  {
    id: 'c3-gyadovilla',
    name: 'Gyado Villa C3',
    zone: 'Gyado Villa',
    meetingAddress: 'Beside Benue State University 2nd Gate, Gyado Villa, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Elder Peter Ochigbo',
    ministerName: 'Minister Peter Ochigbo',
    isActive: true,
  },
  {
    id: 'c3-welfarequarters',
    name: 'Welfare Quarters C3',
    zone: 'Welfare Quarters',
    meetingAddress: 'Welfare Quarters Road, Near Civil Service Commission, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '6:00 PM',
    hostName: 'Deaconess Comfort Chia',
    ministerName: 'Minister Comfort Chia',
    isActive: true,
  },
  {
    id: 'c3-oldgra',
    name: 'Old GRA C3',
    zone: 'Old GRA',
    meetingAddress: 'Kashim Ibrahim Road, Old GRA, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:15 PM',
    hostName: 'Bro. Joshua Terver',
    ministerName: 'Minister Paul Hembadoon',
    isActive: true,
  },
];

export const MOCK_SERVICE_TEAMS: ServiceTeam[] = [
  {
    id: 'team-prayer',
    name: 'Prayer & Counselling',
    code: 'PRAYER',
    description: 'Pre-service intercession, prayer cover for services, follow-up counselling and deliverance ministry',
    leaderName: 'Pastor Mercy Agbese',
    isActive: true,
  },
  {
    id: 'team-music',
    name: 'Music (CFC Music)',
    code: 'MUSIC',
    description: 'Praise, prophetic worship and choir leading the atmosphere of the Holy Spirit during all services',
    leaderName: 'Bro. Gabriel Onoja',
    isActive: true,
  },
  {
    id: 'team-production',
    name: 'Production',
    code: 'PRODUCTION',
    description: 'Sound engineering, acoustics, live multi-camera broadcast, lighting, LED screens and podcasts',
    leaderName: 'Bro. Daniel Aondo',
    isActive: true,
  },
  {
    id: 'team-welfare',
    name: 'Welfare',
    code: 'WELFARE',
    description: 'Hospitality to first timers, benevolence support to members, food pantry, and visitation care',
    leaderName: 'Deaconess Martha Kula',
    isActive: true,
  },
  {
    id: 'team-ushers',
    name: 'Ushering & Protocol',
    code: 'USHERS',
    description: 'Sanctuary seating, welcoming congregants, offering coordination, and guest ministers reception',
    leaderName: 'Sis. Grace Kave',
    isActive: true,
  },
  {
    id: 'team-sanctuary',
    name: 'Sanctuary Keepers',
    code: 'SANCTUARY',
    description: 'Beautification, cleanliness, and ambiance of the church auditorium and church facility',
    leaderName: 'Sis. Esther Igoche',
    isActive: true,
  },
  {
    id: 'team-security',
    name: 'Traffic & Security',
    code: 'SECURITY',
    description: 'Vehicle parking management, perimeter security, surveillance, and safe congregation dispersal',
    leaderName: 'Capt. Isaac Tyopev (Rtd)',
    isActive: true,
  },
];

export const MOCK_MINISTRY_TEAMS: MinistryTeam[] = [
  {
    id: 'min-men',
    name: 'Men of Faith Fellowship',
    code: 'MEN',
    description: 'Empowerment, spiritual mentorship, career growth and family leadership for Christian fathers and men',
    targetAudience: 'Christian Men & Fathers',
    leaderName: 'Elder Abraham Chia',
    isActive: true,
  },
  {
    id: 'min-ladies',
    name: '31st Ladies Fellowship',
    code: 'LADIES',
    description: 'Virtuous women ministry, spiritual retreats, marriage health, and sisterly empowerment',
    targetAudience: 'Christian Women & Mothers',
    leaderName: 'Deaconess Blessing Terungwa',
    isActive: true,
  },
  {
    id: 'min-children',
    name: "Children's Church (Kingdom Kids)",
    code: 'CHILDREN',
    description: 'Age-tailored biblical instruction, foundational discipleship, crafts, and memory verse recitation',
    targetAudience: 'Children aged 1 to 12',
    leaderName: 'Sis. Rosemary Abah',
    isActive: true,
  },
];

export const MOCK_C3_REPORTS: C3Report[] = [
  {
    id: 'c3rep-001',
    c3Id: 'c3-nyiman',
    c3Name: 'Nyiman C3',
    zone: 'Nyiman',
    meetingDate: '2026-09-23',
    topicTaught: 'Walking in Supernatural Dominion: Part 3',
    maleAttendance: 11,
    femaleAttendance: 14,
    childrenAttendance: 7,
    totalAttendance: 32,
    firstTimers: 3,
    newConverts: 1,
    offeringAmount: 18500,
    tithesAmount: 25000,
    prayerRequests: 'Healing for Mama Iorbee admitted at FMC Makurdi. Job breakthrough for Bro Joseph.',
    testimonies: 'Sis. Jennifer testified of surviving a vehicle breakdown on Makurdi-Aliade expressway safely.',
    challengesEncountered: 'Generator fuel price increase affected power during the fellowship.',
    submittedBy: 'user-c3-nyiman',
    submittedByName: 'Minister Faith Terungwa',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'Commended for consistent attendance growth and follow-up on FMC hospital visit.',
    residentPastorNotes: 'Great work Nyiman cell. Pastoral team will visit Mama Iorbee at FMC.',
    createdAt: '2026-09-23T20:30:00Z',
    updatedAt: '2026-09-24T10:15:00Z',
  },
  {
    id: 'c3rep-002',
    c3Id: 'c3-georgeakume',
    c3Name: 'George Akume Way C3',
    zone: 'George Akume Way',
    meetingDate: '2026-09-23',
    topicTaught: 'The Power of Collective Intercession',
    maleAttendance: 9,
    femaleAttendance: 16,
    childrenAttendance: 5,
    totalAttendance: 30,
    firstTimers: 4,
    newConverts: 2,
    offeringAmount: 22000,
    tithesAmount: 15000,
    prayerRequests: 'Prayers for student members taking university semester examinations.',
    testimonies: 'Bro. Terna secured employment with an agribusiness firm in Makurdi.',
    challengesEncountered: 'Space constraints in living room due to growing attendance. Looking at outdoor canopy option.',
    submittedBy: 'user-c3-georgeakume',
    submittedByName: 'Minister Joshua Idoko',
    status: 'reviewed_by_associate',
    associatePastorNotes: 'Recommending cell multiplication into George Akume Way 2 before Q4.',
    createdAt: '2026-09-23T21:10:00Z',
    updatedAt: '2026-09-24T08:30:00Z',
  },
  {
    id: 'c3rep-003',
    c3Id: 'c3-northbank',
    c3Name: 'North Bank C3',
    zone: 'North Bank',
    meetingDate: '2026-09-23',
    topicTaught: 'Faith That Overcomes Trials',
    maleAttendance: 8,
    femaleAttendance: 10,
    childrenAttendance: 6,
    totalAttendance: 24,
    firstTimers: 2,
    newConverts: 0,
    offeringAmount: 12500,
    tithesAmount: 0,
    prayerRequests: 'Peace in surrounding neighborhoods and security along new bypass.',
    testimonies: 'Bro. Emmanuel passed professional licensing board exam.',
    challengesEncountered: 'Heavy downpour starting at 4:45 PM reduced arrival count.',
    submittedBy: 'user-c3-northbank',
    submittedByName: 'Minister Timothy Bem',
    status: 'submitted',
    createdAt: '2026-09-23T22:00:00Z',
    updatedAt: '2026-09-23T22:00:00Z',
  },
  {
    id: 'c3rep-004',
    c3Id: 'c3-gyadovilla',
    c3Name: 'Gyado Villa C3',
    zone: 'Gyado Villa',
    meetingDate: '2026-09-23',
    topicTaught: 'Financial Stewardship and the Blessing',
    maleAttendance: 12,
    femaleAttendance: 15,
    childrenAttendance: 8,
    totalAttendance: 35,
    firstTimers: 5,
    newConverts: 2,
    offeringAmount: 26000,
    tithesAmount: 40000,
    prayerRequests: 'Family reconciliation request for the Agada household.',
    testimonies: 'Safe child delivery for Sis Mercy Ochigbo at Bishop Murray Hospital.',
    challengesEncountered: 'Need more hymn sheets and discipleship manuals for first timers.',
    submittedBy: 'user-c3-gyadovilla',
    submittedByName: 'Minister Peter Ochigbo',
    status: 'submitted',
    createdAt: '2026-09-24T07:45:00Z',
    updatedAt: '2026-09-24T07:45:00Z',
  },
  {
    id: 'c3rep-005',
    c3Id: 'c3-welfarequarters',
    c3Name: 'Welfare Quarters C3',
    zone: 'Welfare Quarters',
    meetingDate: '2026-09-23',
    topicTaught: 'Abiding Under the Shadow of the Almighty',
    maleAttendance: 10,
    femaleAttendance: 13,
    childrenAttendance: 5,
    totalAttendance: 28,
    firstTimers: 3,
    newConverts: 1,
    offeringAmount: 21000,
    tithesAmount: 20000,
    prayerRequests: 'Healing for Bro. Terfa recovering from surgery.',
    testimonies: 'Promotion confirmation at State Ministry of Finance for Deaconess Comfort.',
    challengesEncountered: 'Additional plastic chairs required.',
    submittedBy: 'user-c3-welfarequarters',
    submittedByName: 'Minister Comfort Chia',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'Welfare quarters cell consistently punctual with reports.',
    residentPastorNotes: 'Well done. Keep nurturing the brethren in faith.',
    createdAt: '2026-09-24T08:15:00Z',
    updatedAt: '2026-09-24T11:00:00Z',
  },
  {
    id: 'c3rep-006',
    c3Id: 'c3-oldgra',
    c3Name: 'Old GRA C3',
    zone: 'Old GRA',
    meetingDate: '2026-09-23',
    topicTaught: 'The Covenant of Peace and Prosperity',
    maleAttendance: 9,
    femaleAttendance: 11,
    childrenAttendance: 4,
    totalAttendance: 24,
    firstTimers: 2,
    newConverts: 1,
    offeringAmount: 32000,
    tithesAmount: 50000,
    prayerRequests: 'Traveling mercies for members embarking on trips to Abuja and Lagos.',
    testimonies: 'God answered prayer for admission into professional postgraduate school.',
    challengesEncountered: 'Street lighting needs improvement near venue.',
    submittedBy: 'user-c3-oldgra',
    submittedByName: 'Minister Paul Hembadoon',
    status: 'reviewed_by_associate',
    associatePastorNotes: 'High giving and dedication noted.',
    createdAt: '2026-09-24T08:45:00Z',
    updatedAt: '2026-09-24T09:30:00Z',
  },
];

export const MOCK_SERVICE_TEAM_REPORTS: ServiceTeamReport[] = [
  {
    id: 'st-rep-001',
    teamId: 'team-prayer',
    teamName: 'Prayer & Counselling',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 16,
    rosterAbsentCount: 1,
    totalOnDuty: 16,
    tasksCompleted: 'Conducted 6:00 AM pre-service prayer vigil. Interceded during praise, word, and altarcall. Counselled 17 altar call converts and 12 brethren in prayer room.',
    equipmentStatus: 'Prayer room sound monitors and counselling intake sheets were properly set up.',
    challengesEncountered: 'Need more private counselling cubicles as demand for one-on-one sessions was very high.',
    urgentNeeds: 'Additional 50 convert decision counselling booklets.',
    submittedBy: 'user-team-prayer',
    submittedByName: 'Pastor Mercy Agbese',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'Prayer atmosphere was deep and effective. Convert follow-up booklets approved.',
    residentPastorNotes: 'Commended. Pastoral counseling team is vital to fruit that remains.',
    createdAt: '2026-09-27T12:00:00Z',
    updatedAt: '2026-09-27T15:00:00Z',
  },
  {
    id: 'st-rep-002',
    teamId: 'team-music',
    teamName: 'Music (CFC Music)',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 28,
    rosterAbsentCount: 2,
    totalOnDuty: 28,
    tasksCompleted: 'Led powerful 40-minute praise & prophetic worship. Rendered special song "Lord You Reign in Glory". Backed up altar call ministration.',
    equipmentStatus: 'All in-ear monitors functioned properly. Main keyboard sustain pedal replaced.',
    challengesEncountered: 'Acoustics in overflow wing need fine-tuning with sound engineers.',
    urgentNeeds: 'Replacement 9V rechargeable batteries for wireless microphones.',
    submittedBy: 'user-team-music',
    submittedByName: 'Bro. Gabriel Onoja',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'The prophetic worship set set the stage for the Word. Battery purchase approved.',
    residentPastorNotes: 'Outstanding worship ministration. Atmosphere of joy was palpable.',
    createdAt: '2026-09-27T12:30:00Z',
    updatedAt: '2026-09-27T16:00:00Z',
  },
  {
    id: 'st-rep-003',
    teamId: 'team-production',
    teamName: 'Production',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 15,
    rosterAbsentCount: 1,
    totalOnDuty: 15,
    tasksCompleted: 'Multi-camera Full HD broadcast on YouTube, Mixlr, and Facebook Live. Audio multitrack recorded. Managed LED screens and lyric projections seamlessly.',
    equipmentStatus: 'Main digital mixer firmware running smoothly. PTZ Camera 3 calibrated.',
    challengesEncountered: 'Internet ISP had a 5-second fluctuation during the opening announcement; backup cellular router took over automatically.',
    urgentNeeds: 'Additional HDMI cable extensions and SSD storage drives for sermon archiving.',
    submittedBy: 'user-team-production',
    submittedByName: 'Bro. Daniel Aondo',
    status: 'reviewed_by_associate',
    associatePastorNotes: 'Excellent swift failover during internet fluctuation. Requisition for SSD drives noted.',
    createdAt: '2026-09-27T13:45:00Z',
    updatedAt: '2026-09-27T14:30:00Z',
  },
  {
    id: 'st-rep-004',
    teamId: 'team-welfare',
    teamName: 'Welfare',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 14,
    rosterAbsentCount: 1,
    totalOnDuty: 14,
    tasksCompleted: 'Hosted 48 first timers in the hospitality lounge with light refreshments and welcome cards. Distributed 15 benevolence care packages to nursing mothers and elders.',
    equipmentStatus: 'Hospitality lounge water dispenser and tea station functional.',
    challengesEncountered: 'Lounge capacity was tight due to high number of first-time visitors (48 guests).',
    urgentNeeds: 'Restock of bottled water, branded gift packs, and contact slip forms.',
    submittedBy: 'user-team-welfare',
    submittedByName: 'Deaconess Martha Kula',
    status: 'approved_by_resident_pastor',
    associatePastorNotes: 'First timer reception received very positive feedback. Requisition for packs forwarded to accounts.',
    residentPastorNotes: 'Love in action! Excellent reception of the new souls.',
    createdAt: '2026-09-27T14:15:00Z',
    updatedAt: '2026-09-27T16:20:00Z',
  },
  {
    id: 'st-rep-005',
    teamId: 'team-ushers',
    teamName: 'Ushering & Protocol',
    serviceDate: '2026-09-27',
    serviceType: 'first_service',
    rosterPresentCount: 24,
    rosterAbsentCount: 2,
    totalOnDuty: 24,
    tasksCompleted: 'Orchestrated seating for 701 worshippers. Seamlessly collected 3 offerings. Coordinated guest pastors protocol and altarcall counseling ushering.',
    equipmentStatus: 'Offering pouches and guest protocol lapel badges in good condition.',
    challengesEncountered: 'Right wing overflow filled early; moved extra 50 chairs from basement.',
    urgentNeeds: 'Additional 20 ushering badges and hand sanitizing units.',
    submittedBy: 'user-team-ushers',
    submittedByName: 'Sis. Grace Kave',
    status: 'submitted',
    createdAt: '2026-09-27T14:45:00Z',
    updatedAt: '2026-09-27T14:45:00Z',
  },
];

export const MOCK_MINISTRY_REPORTS: MinistryReport[] = [
  {
    id: 'minrep-001',
    ministryId: 'min-men',
    ministryName: 'Men of Faith Fellowship',
    meetingDate: '2026-09-20',
    reportTitle: 'September Men Breakfast & Wealth Creation Summit',
    totalAttendance: 78,
    firstTimers: 9,
    offeringAmount: 95000,
    activitiesSummary: 'Organized practical business seminar on Commercial Grain Storage & Distribution in Benue State. Followed by intense prayer for family prosperity.',
    spiritualHighlights: '3 men dedicated their businesses to the Lord; one brother received salvation during the breakfast session.',
    upcomingPrograms: 'Annual Men of Faith Camp Retreat scheduled for November 14-16 at Canaan Land Camp, Makurdi.',
    challengesAndRequests: 'Requesting church bus support for transporting men living in North Bank and Gyado Villa for the upcoming retreat.',
    submittedBy: 'user-ministry-men',
    submittedByName: 'Elder Abraham Chia',
    status: 'approved_by_resident_pastor',
    pastoralNotes: 'Excellent initiative connecting faith and economic empowerment. Church bus logistics approved for the retreat.',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-21T18:00:00Z',
  },
  {
    id: 'minrep-002',
    ministryId: 'min-ladies',
    ministryName: '31st Ladies Fellowship',
    meetingDate: '2026-09-19',
    reportTitle: 'Monthly Daughters of Zion Prayer Vigil & Health Screening',
    totalAttendance: 112,
    firstTimers: 14,
    offeringAmount: 82000,
    activitiesSummary: 'Free blood pressure and diabetes screening for mothers. Spiritual charge on "The Deborah Anointing in Trying Times" delivered by Resident Pastor\'s Wife.',
    spiritualHighlights: 'Strong move of the Spirit during the midnight intercessory session for marital breakthroughs.',
    upcomingPrograms: 'Widows and Elderly Care Outreach scheduled for October 10th.',
    challengesAndRequests: 'Need welfare pantry replenishment of food grains (rice, beans, yams) for the October outreach.',
    submittedBy: 'user-ministry-ladies',
    submittedByName: 'Deaconess Blessing Terungwa',
    status: 'approved_by_resident_pastor',
    pastoralNotes: 'Commended for combining medical checkups with intense prayers. Welfare department has been instructed to partner on grain provision.',
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-09-21T14:30:00Z',
  },
  {
    id: 'minrep-003',
    ministryId: 'min-children',
    ministryName: "Children's Church (Kingdom Kids)",
    meetingDate: '2026-09-27',
    reportTitle: 'Sunday School & Kingdom Kids Celebration',
    totalAttendance: 146,
    firstTimers: 18,
    offeringAmount: 24500,
    activitiesSummary: 'Age-graded bible classes (Toddlers, Beginners, Primaries, Juniors). Theme: "David and Goliath - Courage to Overcome". Color-in memory verse booklets.',
    spiritualHighlights: '12 older children (Ages 9-11) recited the entire Psalm 91 from memory.',
    upcomingPrograms: 'Children Christmas Musical Drama rehearsals starting first week of October.',
    challengesAndRequests: 'Need 2 additional teachers for the Beginner class (Ages 3-5) to maintain ideal teacher-to-child ratio.',
    submittedBy: 'user-ministry-children',
    submittedByName: 'Sis. Rosemary Abah',
    status: 'submitted',
    createdAt: '2026-09-27T13:45:00Z',
    updatedAt: '2026-09-27T13:45:00Z',
  },
];

export const MOCK_GENERAL_SERVICES: GeneralServiceReport[] = [
  {
    id: 'gen-001',
    serviceDate: '2026-09-27',
    serviceType: 'prayer_and_communion',
    preacher: 'Pastor David Terzungwe',
    sermonTitle: 'Unlocking Supernatural Supply in Economic Seasons',
    maleCount: 245,
    femaleCount: 310,
    childrenCount: 146,
    totalAttendance: 701,
    firstTimersCount: 48,
    newConvertsCount: 17,
    totalOffering: 385000,
    totalTithe: 760000,
    notes: 'Last Sunday of the Month Prayer & Communion Service — All 6 C3 Community Churches gathered together in one celebration. Holy Communion ministered with intense prayer sessions.',
    submittedByName: 'Pastor David Terzungwe',
    createdAt: '2026-09-27T14:30:00Z',
  },
  {
    id: 'gen-002',
    serviceDate: '2026-09-20',
    serviceType: 'connect_to_life_first',
    preacher: 'Pastor Emmanuel Ogwuche',
    sermonTitle: 'The Believer’s Covenant Immunity',
    maleCount: 230,
    femaleCount: 295,
    childrenCount: 138,
    totalAttendance: 663,
    firstTimersCount: 36,
    newConvertsCount: 11,
    totalOffering: 340000,
    totalTithe: 620000,
    notes: 'Connect to Life Sunday Service (1st Service). Powerful worship and life-transforming teaching.',
    submittedByName: 'Pastor Emmanuel Ogwuche',
    createdAt: '2026-09-20T14:00:00Z',
  },
  {
    id: 'gen-003',
    serviceDate: '2026-09-13',
    serviceType: 'connect_to_life_first',
    preacher: 'Pastor David Terzungwe',
    sermonTitle: 'Empowered for Exploits',
    maleCount: 218,
    femaleCount: 280,
    childrenCount: 125,
    totalAttendance: 623,
    firstTimersCount: 29,
    newConvertsCount: 8,
    totalOffering: 310000,
    totalTithe: 540000,
    notes: 'Connect to Life Sunday Service (1st Service). High student mobilization from Gyado Villa and North Bank.',
    submittedByName: 'Pastor David Terzungwe',
    createdAt: '2026-09-13T14:15:00Z',
  },
];

export const ATTENDANCE_TREND_DATA = [
  { week: 'Wk 1 (Sep 6)', Sunday: 590, C3Cells: 135, Volunteers: 84 },
  { week: 'Wk 2 (Sep 13)', Sunday: 623, C3Cells: 146, Volunteers: 88 },
  { week: 'Wk 3 (Sep 20)', Sunday: 663, C3Cells: 160, Volunteers: 92 },
  { week: 'Wk 4 (Sep 27)', Sunday: 701, C3Cells: 173, Volunteers: 97 },
];

export const C3_BREAKDOWN_DATA = [
  { name: 'Nyiman', attendance: 32, converts: 1, firstTimers: 3, offering: 18500 },
  { name: 'George Akume', attendance: 30, converts: 2, firstTimers: 4, offering: 22000 },
  { name: 'North Bank', attendance: 24, converts: 0, firstTimers: 2, offering: 12500 },
  { name: 'Gyado Villa', attendance: 35, converts: 2, firstTimers: 5, offering: 26000 },
  { name: 'Welfare Qtrs', attendance: 28, converts: 1, firstTimers: 3, offering: 21000 },
  { name: 'Old GRA', attendance: 24, converts: 1, firstTimers: 2, offering: 32000 },
];
