import {
  UserProfile,
  C3Centre,
  ServiceTeam,
  MinistryTeam,
  C3Report,
  ServiceTeamReport,
  MinistryReport,
  GeneralServiceReport,
} from './types';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user-resident-pastor',
    fullName: 'Pastor David Terzungwe',
    email: 'resident.pastor@cfcmakurdi.org',
    phone: '+234 803 123 4567',
    role: 'resident_pastor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-pastor-tokula',
    fullName: 'Pastor Arome Tokula',
    email: 'pastor.tokula@cfcmakurdi.org',
    phone: '+234 803 000 0001',
    role: 'resident_pastor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-assoc-c3',
    fullName: 'Pastor Emmanuel Ogwuche',
    email: 'assoc.c3@cfcmakurdi.org',
    phone: '+234 802 234 5678',
    role: 'associate_pastor_c3',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-assoc-teams',
    fullName: 'Pastor Samuel Iorkase',
    email: 'assoc.teams@cfcmakurdi.org',
    phone: '+234 805 345 6789',
    role: 'associate_pastor_service_teams',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-c3-nyiman',
    fullName: 'Minister Faith Terungwa',
    email: 'faith.nyiman@cfcmakurdi.org',
    phone: '+234 813 456 7890',
    role: 'c3_minister',
    c3Id: 'c3-nyiman',
    c3Name: 'Nyiman C3',
  },
  {
    id: 'user-c3-georgeakume',
    fullName: 'Minister Joshua Idoko',
    email: 'joshua.gakume@cfcmakurdi.org',
    phone: '+234 814 567 8901',
    role: 'c3_minister',
    c3Id: 'c3-georgeakume',
    c3Name: 'George Akume Way C3',
  },
  {
    id: 'user-c3-northbank',
    fullName: 'Minister Timothy Bem',
    email: 'timothy.northbank@cfcmakurdi.org',
    phone: '+234 815 678 1234',
    role: 'c3_minister',
    c3Id: 'c3-northbank',
    c3Name: 'North Bank C3',
  },
  {
    id: 'user-c3-gyadovilla',
    fullName: 'Minister Peter Ochigbo',
    email: 'peter.gyadovilla@cfcmakurdi.org',
    phone: '+234 816 789 2345',
    role: 'c3_minister',
    c3Id: 'c3-gyadovilla',
    c3Name: 'Gyado Villa C3',
  },
  {
    id: 'user-c3-welfarequarters',
    fullName: 'Minister Comfort Chia',
    email: 'comfort.welfareqtrs@cfcmakurdi.org',
    phone: '+234 817 890 3456',
    role: 'c3_minister',
    c3Id: 'c3-welfarequarters',
    c3Name: 'Welfare Quarters C3',
  },
  {
    id: 'user-c3-oldgra',
    fullName: 'Minister Paul Hembadoon',
    email: 'paul.oldgra@cfcmakurdi.org',
    phone: '+234 818 901 4567',
    role: 'c3_minister',
    c3Id: 'c3-oldgra',
    c3Name: 'Old GRA C3',
  },
  {
    id: 'user-team-prayer',
    fullName: 'Pastor Mercy Agbese',
    email: 'prayer.lead@cfcmakurdi.org',
    phone: '+234 819 012 5678',
    role: 'service_team_leader',
    serviceTeamId: 'team-prayer',
    serviceTeamName: 'Prayer & Counselling',
  },
  {
    id: 'user-team-music',
    fullName: 'Bro. Gabriel Onoja',
    email: 'music.lead@cfcmakurdi.org',
    phone: '+234 816 678 9012',
    role: 'service_team_leader',
    serviceTeamId: 'team-music',
    serviceTeamName: 'Music (CFC Music)',
  },
  {
    id: 'user-team-production',
    fullName: 'Bro. Daniel Aondo',
    email: 'production.lead@cfcmakurdi.org',
    phone: '+234 818 890 1234',
    role: 'service_team_leader',
    serviceTeamId: 'team-production',
    serviceTeamName: 'Production (Media & Sound)',
  },
  {
    id: 'user-team-welfare',
    fullName: 'Deaconess Martha Kula',
    email: 'welfare.lead@cfcmakurdi.org',
    phone: '+234 817 789 0123',
    role: 'service_team_leader',
    serviceTeamId: 'team-welfare',
    serviceTeamName: 'Welfare',
  },
  {
    id: 'user-team-ushers',
    fullName: 'Sis. Grace Kave',
    email: 'ushering.lead@cfcmakurdi.org',
    phone: '+234 812 345 6789',
    role: 'service_team_leader',
    serviceTeamId: 'team-ushers',
    serviceTeamName: 'Ushering & Protocol',
  },
  {
    id: 'user-ministry-men',
    fullName: 'Elder Abraham Chia',
    email: 'men.fellowship@cfcmakurdi.org',
    phone: '+234 809 901 2345',
    role: 'ministry_leader',
    ministryId: 'min-men',
    ministryName: 'Men of Faith Fellowship',
  },
  {
    id: 'user-ministry-ladies',
    fullName: 'Deaconess Blessing Terungwa',
    email: '31stladies@cfcmakurdi.org',
    phone: '+234 808 012 3456',
    role: 'ministry_leader',
    ministryId: 'min-ladies',
    ministryName: '31st Ladies Fellowship',
  },
  {
    id: 'user-ministry-children',
    fullName: 'Sis. Rosemary Abah',
    email: 'children.church@cfcmakurdi.org',
    phone: '+234 807 123 9876',
    role: 'ministry_leader',
    ministryId: 'min-children',
    ministryName: "Children's Church (Kingdom Kids)",
  },
];

export const MOCK_C3_CENTRES: C3Centre[] = [
  {
    id: 'c3-nyiman',
    name: 'Nyiman C3',
    zone: 'Nyiman',
    meetingAddress: 'Off Abu King Shuluwa Road, Nyiman Layout, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Bro. Terungwa Aondo',
    ministerName: 'Minister Faith Terungwa',
    isActive: true,
  },
  {
    id: 'c3-georgeakume',
    name: 'George Akume Way C3',
    zone: 'George Akume Way',
    meetingAddress: 'Near New Garage Junction, George Akume Way, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:30 PM',
    hostName: 'Sis. Deborah Iorhemen',
    ministerName: 'Minister Joshua Idoko',
    isActive: true,
  },
  {
    id: 'c3-northbank',
    name: 'North Bank C3',
    zone: 'North Bank',
    meetingAddress: 'Near University of Agriculture Road, North Bank, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Bro. Emmanuel Agbo',
    ministerName: 'Minister Timothy Bem',
    isActive: true,
  },
  {
    id: 'c3-gyadovilla',
    name: 'Gyado Villa C3',
    zone: 'Gyado Villa',
    meetingAddress: 'Beside Benue State University 2nd Gate, Gyado Villa, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:00 PM',
    hostName: 'Elder Peter Ochigbo',
    ministerName: 'Minister Peter Ochigbo',
    isActive: true,
  },
  {
    id: 'c3-welfarequarters',
    name: 'Welfare Quarters C3',
    zone: 'Welfare Quarters',
    meetingAddress: 'Welfare Quarters Road, Near Civil Service Commission, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '6:00 PM',
    hostName: 'Deaconess Comfort Chia',
    ministerName: 'Minister Comfort Chia',
    isActive: true,
  },
  {
    id: 'c3-oldgra',
    name: 'Old GRA C3',
    zone: 'Old GRA',
    meetingAddress: 'Kashim Ibrahim Road, Old GRA, Makurdi',
    meetingDay: 'Wednesday',
    meetingTime: '5:15 PM',
    hostName: 'Bro. Joshua Terver',
    ministerName: 'Minister Paul Hembadoon',
    isActive: true,
  },
];

export const MOCK_SERVICE_TEAMS: ServiceTeam[] = [
  {
    id: 'team-prayer',
    name: 'Prayer & Counselling',
    code: 'PRAYER',
    description: 'Pre-service intercession, prayer cover for services, follow-up counselling and deliverance ministry',
    leaderName: 'Pastor Mercy Agbese',
    isActive: true,
  },
  {
    id: 'team-music',
    name: 'Music (CFC Music)',
    code: 'MUSIC',
    description: 'Praise, prophetic worship and choir leading the atmosphere of the Holy Spirit during all services',
    leaderName: 'Bro. Gabriel Onoja',
    isActive: true,
  },
  {
    id: 'team-production',
    name: 'Production',
    code: 'PRODUCTION',
    description: 'Sound engineering, acoustics, live multi-camera broadcast, lighting, LED screens and podcasts',
    leaderName: 'Bro. Daniel Aondo',
    isActive: true,
  },
  {
    id: 'team-welfare',
    name: 'Welfare',
    code: 'WELFARE',
    description: 'Hospitality to first timers, benevolence support to members, food pantry, and visitation care',
    leaderName: 'Deaconess Martha Kula',
    isActive: true,
  },
  {
    id: 'team-ushers',
    name: 'Ushering & Protocol',
    code: 'USHERS',
    description: 'Sanctuary seating, welcoming congregants, offering coordination, and guest ministers reception',
    leaderName: 'Sis. Grace Kave',
    isActive: true,
  },
  {
    id: 'team-sanctuary',
    name: 'Sanctuary Keepers',
    code: 'SANCTUARY',
    description: 'Beautification, cleanliness, and ambiance of the church auditorium and church facility',
    leaderName: 'Sis. Esther Igoche',
    isActive: true,
  },
  {
    id: 'team-security',
    name: 'Traffic & Security',
    code: 'SECURITY',
    description: 'Vehicle parking management, perimeter security, surveillance, and safe congregation dispersal',
    leaderName: 'Capt. Isaac Tyopev (Rtd)',
    isActive: true,
  },
];

export const MOCK_MINISTRY_TEAMS: MinistryTeam[] = [
  {
    id: 'min-men',
    name: 'Men of Faith Fellowship',
    code: 'MEN',
    description: 'Empowerment, spiritual mentorship, career growth and family leadership for Christian fathers and men',
    targetAudience: 'Christian Men & Fathers',
    leaderName: 'Elder Abraham Chia',
    isActive: true,
  },
  {
    id: 'min-ladies',
    name: '31st Ladies Fellowship',
    code: 'LADIES',
    description: 'Virtuous women ministry, spiritual retreats, marriage health, and sisterly empowerment',
    targetAudience: 'Christian Women & Mothers',
    leaderName: 'Deaconess Blessing Terungwa',
    isActive: true,
  },
  {
    id: 'min-children',
    name: "Children's Church (Kingdom Kids)",
    code: 'CHILDREN',
    description: 'Age-tailored biblical instruction, foundational discipleship, crafts, and memory verse recitation',
    targetAudience: 'Children aged 1 to 12',
    leaderName: 'Sis. Rosemary Abah',
    isActive: true,
  },
];

export const MOCK_C3_REPORTS: C3Report[] = [];

export const MOCK_SERVICE_TEAM_REPORTS: ServiceTeamReport[] = [];

export const MOCK_MINISTRY_REPORTS: MinistryReport[] = [];

export const MOCK_GENERAL_SERVICES: GeneralServiceReport[] = [];

export const ATTENDANCE_TREND_DATA: { week: string; Sunday: number; C3Cells: number; Volunteers: number }[] = [];

export const C3_BREAKDOWN_DATA: { name: string; attendance: number; converts: number; firstTimers: number; offering: number }[] = [];
